---

# MODULES
modules:
  phylogeny: true # 
  report: true # 
  subsampling: false # Perform a subsampling before tree (dafault: false)
  phylodynamie: true # Perform a phylodynamic analysis (default: false)

# MY ENVS
envs:
  mafft:    "../envs/mafft.yaml"
  treetime: "../envs/treetime.yaml"
  gblocks:  "../envs/gblocks.yaml"
  iqtree:   "../envs/iqtree.yaml"
  seqkit:   "../envs/seqkit.yaml"
  ancestral_changes: "../envs/ancestral_changes.yaml"

# MY SAMPLES
samples: # choose samples to run the pipeline, available options:
   - 'alpha' # default
   - 'beta'
   - 'gamma'
   #- 'yours' # custom


######################################
# DRAFT FOR LATER #
###################
resources:
  threads: 4
  memory: 8G
  time: 1-00:00:00


params:
  iqtree:
    threads: 4
    model: 'GTR+G'
    bootstrap: 100
    seed: 12345
  gblocks:
    type: 'd'   # d = DNA, p = protein, c = codon
    b5: 'h'     # h = half, n = strict
  treetime:
    seq_len: 29650 # minimum sequence length in bp (default: 29000) [INT]
    clock_rate: 0.008 # clock rate in subs per site per year (default: 0.001) [FLOAT]
    clock_std_dev: 0.0035
    attribute: "country"
  mafft:    
    threads: 4  
  absolute_time:
    #date: 2021.7 # date of the most recent sample in the dataset
    #file: 'results/00_Dataset/alpha_metadata.tsv' # date of the most recent sample in the dataset